### ISSUE TITLE
Can you provide a GIAS data set that you divided when training GIAS? 

### ISSUE THREAD

**Issue by jane442** [McGregorWwww/UCTransNet#13]
Hello author, can you provide a GIAS data set that you divided when training GIAS? My email is 1458546594@qq.com, if possible, I will be very grateful to you

**Comment by McGregorWwww** [comment]
Thanks for your attention. Actually, in the latest version of our paper, we use three times five-fold cross validations to make the results in the small datasets more convincing. I highly recommend you to do so as well, because the results seem quite unstable due to the small number of data. Hope this helps.

**Comment by jane442** [comment]
Hello,author, could you provide the latest code, the code related to the three times five-fold cross validations?,or can you send me a copy of the latest code, my email is  1458546594@qq.com,thank you very much!

**Comment by mustansarfiaz** [comment]
Hello,author, 

could you provide the latest code, the code related to the three times five-fold cross validations?,or can you send me a copy of the latest code, my email is [mustansar.fiaz@gmail.com](mailto:mustansar.fiaz@gmail.com)

Regards:
Mustansar

**Comment by McGregorWwww** [comment]
For the five-fold cross validation pipeline, you can refer to this repo: https://github.com/McGregorWwww/UDTransNet

For the three times experiment, you can just run the pipeline three times and average all the results. Note that this may not be necessary in your tasks, since we added this  exp mainly to convince the reviewer.
