### ISSUE TITLE
Early stop

### ISSUE THREAD

**Issue by h1063135843** [McGregorWwww/UCTransNet#8]
I trained the Unet in your implemantation.
And test result:
dice_pred 0.7823487865522568
iou_pred 0.649269364395218

UNet is even better than the uctransnet model I trained and slightly lower than the model you provide
uctransnet  trained from default config.
dice_pred 0.7601493846752263
iou_pred 0.6263514063702118

Both training encounter the early stop(around 120 epoch, and default is 2000)
What's the problem?

**Comment by saleknia** [comment]
It has happened also for me and It's so weird because this simple implementation of UNet with very limited parameters can overcome UCTransNet on Synapse dataset and even TransUNet. Do you think what is the problem?

**Comment by McGregorWwww** [comment]
Thanks for your attention. The problem may caused by different version of CUDA, GPU, parameter settings and etc. which may further cause the randomness during the training stage. This problem is more severe in small datasets. In the latest version of the paper, I use series of cross validations and take the mean score and std to alleviate this problem, which can make the results more stable and convincing. Hope this helps.
